### ISSUE TITLE
Evalueren en aanpassen van groottes van schermelementen (buttons, pop-up schermen)

### ISSUE THREAD

**Issue by RumiaGIT** [Proliner/omoda#22]
- Blijft de tekst leesbaar in verschillende schermen.
- Blijven de knoppen en elementen goed aanklikbaar.

**Comment by Proliner** [comment]
- [ ] App doorgenomen
- [ ] Dingen die opvallen en niet gebruikersvriendelijk zijn genoteerd
- [ ] Issues aanmaken
