### ISSUE TITLE
Onderzoek werking app met spiegel

### ISSUE THREAD

**Issue by HoogendoornM** [Proliner/omoda#39]
Als gebruiker wil ik de virtuele schoenen kunnen bekijken in een spiegel, zodat ik de schoenen kan matchen met mijn outfit.

Beantwoorden van de volgende vragen:

- Werkt de ground-tracking in een spiegel? 

- Werkt de Imagetracking in de spiegel? 
- Moet de tracking afbeelding aangepast worden om de tracking te laten werken?

**Comment by Proliner** [comment]
Klant is op de hoogte
